apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logstash
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:siripongn/kubemetrics.git
    targetRevision: HEAD
    path: logstash
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    # syncOption:
    # - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true