kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # kubeadmConfigPatches:
  # - |
  #   kind: InitConfiguration
  #   nodeRegistration:
  #     kubeletExtraArgs:
  #       node-labels: "ingress-ready=true"
- role: worker
- role: worker
# kind create cluster --name monitoring --image kindest/node:v1.26.0 --config kind.yml
# kind get clusters
# kubectl cluster-info --context kind-[cluster-name]