apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  # nodeSelector:
  #   disktype: ssd
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - store
        topologyKey: "kubernetes.io/hostname"

  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: disktype
  #           operator: In
  #           values:
  #           - ssd

  
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
